channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10
  - ipykernel
  - nbformat
  - healpy
  - pip
  - pip:
      - lxml
      - earthkit==0.11.2
      - earthkit-plots==0.4.0
      - covjsonkit>=0.2.5
      - polytope-client
      - earthkit-geo
      - kaleido
      - h3
      - rasterio
